//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicalFit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Athletes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Athletes()
        {
            this.Users = new HashSet<Users>();
            this.GeneralTrainingRecord = new HashSet<GeneralTrainingRecord>();
            this.DetectionTrainingRecord = new HashSet<DetectionTrainingRecord>();
            this.ShootingRecord = new HashSet<ShootingRecord>();
            this.ArcheryRecord = new HashSet<ArcheryRecord>();
            this.SessionTrainingRecords = new HashSet<SessionTrainingRecords>();
        }
    
        public int ID { get; set; }
        public string AthleteAccount { get; set; }
        public string AthletePWD { get; set; }
        public string AthleteName { get; set; }
        public string AthleteSchool { get; set; }
        public string TeamName { get; set; }
        public Nullable<int> CoachID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime Birthday { get; set; }
        public string IdentityNumber { get; set; }
    
        public virtual Coaches Coaches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users> Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GeneralTrainingRecord> GeneralTrainingRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetectionTrainingRecord> DetectionTrainingRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShootingRecord> ShootingRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArcheryRecord> ArcheryRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionTrainingRecords> SessionTrainingRecords { get; set; }
    }
}
