//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicalFit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AthleteCoachRelations
    {
        public int ID { get; set; }
        public int AthleteID { get; set; }
        public int CoachID { get; set; }
    
        public virtual Athletes Athletes { get; set; }
        public virtual Coaches Coaches { get; set; }
    }
}
