//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicalFit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BikeRecordDetails
    {
        public int Id { get; set; }
        public int DetectionTrainingRecordId { get; set; }
        public string MaxPower { get; set; }
        public string IntenPercen { get; set; }
        public int ForceDuration { get; set; }
        public double Speed { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> TrainingDateTime { get; set; }
    
        public virtual DetectionTrainingRecord DetectionTrainingRecord { get; set; }
    }
}
