//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicalFit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coaches
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Coaches()
        {
            this.Athletes = new HashSet<Athletes>();
            this.Users = new HashSet<Users>();
            this.GeneralTrainingRecord = new HashSet<GeneralTrainingRecord>();
            this.DetectionTrainingRecord = new HashSet<DetectionTrainingRecord>();
            this.ShootingRecord = new HashSet<ShootingRecord>();
            this.ArcheryRecord = new HashSet<ArcheryRecord>();
            this.SessionTrainingRecords = new HashSet<SessionTrainingRecords>();
        }
    
        public int ID { get; set; }
        public string CoachName { get; set; }
        public string Email { get; set; }
        public string CoachPwd { get; set; }
        public string SchoolName { get; set; }
        public string SchoolID { get; set; }
        public string PhoneNumber { get; set; }
        public string Title { get; set; }
        public string TeamName { get; set; }
        public string SportsSpecific { get; set; }
        public bool IsActive { get; set; }
        public string CoachAccount { get; set; }
        public System.DateTime RegistrationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Athletes> Athletes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users> Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GeneralTrainingRecord> GeneralTrainingRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetectionTrainingRecord> DetectionTrainingRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShootingRecord> ShootingRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArcheryRecord> ArcheryRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionTrainingRecords> SessionTrainingRecords { get; set; }
    }
}
