//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicalFit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetectionTrainingRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetectionTrainingRecord()
        {
            this.CyclingRecord = new HashSet<CyclingRecord>();
            this.RollerSkiingRecord = new HashSet<RollerSkiingRecord>();
            this.RunningMachineRecord = new HashSet<RunningMachineRecord>();
            this.SwimmingRecord = new HashSet<SwimmingRecord>();
            this.TrackFieldRecord = new HashSet<TrackFieldRecord>();
        }
    
        public int ID { get; set; }
        public string Coach { get; set; }
        public Nullable<int> CoachID { get; set; }
        public string Athlete { get; set; }
        public Nullable<int> AthleteID { get; set; }
        public Nullable<System.DateTime> TrainingDate { get; set; }
        public string DetectionItem { get; set; }
        public string SportItem { get; set; }
        public Nullable<double> CriticalSpeed { get; set; }
        public Nullable<double> MaxAnaerobicWork { get; set; }
        public Nullable<double> TrainingVolume { get; set; }
        public Nullable<double> TrainingPrescription { get; set; }
        public Nullable<double> CoefficientOfDetermination { get; set; }
    
        public virtual Coaches Coaches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CyclingRecord> CyclingRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RollerSkiingRecord> RollerSkiingRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RunningMachineRecord> RunningMachineRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwimmingRecord> SwimmingRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrackFieldRecord> TrackFieldRecord { get; set; }
        public virtual Athletes Athletes { get; set; }
    }
}
