//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicalFit.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PhFitnessEntities : DbContext
    {
        public PhFitnessEntities()
            : base("name=PhFitnessEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Permissions> Permissions { get; set; }
        public virtual DbSet<UserPermissions> UserPermissions { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<TrainingPurpose> TrainingPurpose { get; set; }
        public virtual DbSet<AbilityDetermination> AbilityDetermination { get; set; }
        public virtual DbSet<ArcheryTraining> ArcheryTraining { get; set; }
        public virtual DbSet<IntensityClassification> IntensityClassification { get; set; }
        public virtual DbSet<MusclePhysical> MusclePhysical { get; set; }
        public virtual DbSet<RPE> RPE { get; set; }
        public virtual DbSet<ShootingTraining> ShootingTraining { get; set; }
        public virtual DbSet<SpecializedTraining> SpecializedTraining { get; set; }
        public virtual DbSet<TechnologyCategory> TechnologyCategory { get; set; }
        public virtual DbSet<TrainingTimes> TrainingTimes { get; set; }
        public virtual DbSet<TrainingItems> TrainingItems { get; set; }
        public virtual DbSet<TrainingMonitoringItems> TrainingMonitoringItems { get; set; }
        public virtual DbSet<ShottingItems> ShottingItems { get; set; }
        public virtual DbSet<DetectionSys> DetectionSys { get; set; }
        public virtual DbSet<SessionRPETrainingRecords> SessionRPETrainingRecords { get; set; }
        public virtual DbSet<DetectionTraining> DetectionTraining { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<PasswordResetRequests> PasswordResetRequests { get; set; }
        public virtual DbSet<MixedStrength> MixedStrength { get; set; }
        public virtual DbSet<MuscleStrength> MuscleStrength { get; set; }
        public virtual DbSet<PhysicalFitness> PhysicalFitness { get; set; }
        public virtual DbSet<SpecialTechnical> SpecialTechnical { get; set; }
        public virtual DbSet<SpecialTechnicalAction> SpecialTechnicalAction { get; set; }
        public virtual DbSet<PrimarySchoolList> PrimarySchoolList { get; set; }
        public virtual DbSet<ComprehensiveHighSchoolList> ComprehensiveHighSchoolList { get; set; }
        public virtual DbSet<GeneralHighSchoolList> GeneralHighSchoolList { get; set; }
        public virtual DbSet<JuniorHighSchoolList> JuniorHighSchoolList { get; set; }
        public virtual DbSet<UniversitySchoolList> UniversitySchoolList { get; set; }
        public virtual DbSet<Athletes> Athletes { get; set; }
        public virtual DbSet<Coaches> Coaches { get; set; }
    }
}
