//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicalFit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralTrainingRecord
    {
        public int ID { get; set; }
        public Nullable<int> CoachID { get; set; }
        public Nullable<int> AthleteID { get; set; }
        public string TrainingClassName { get; set; }
        public Nullable<System.DateTime> TrainingDate { get; set; }
        public string TrainingItem { get; set; }
        public string ActionName { get; set; }
        public string TrainingParts { get; set; }
        public string TrainingType { get; set; }
        public string TrainingOther { get; set; }
        public string TrainingTime { get; set; }
        public Nullable<int> RPEscore { get; set; }
        public Nullable<int> EachTrainingLoad { get; set; }
        public Nullable<int> DailyTrainingLoad { get; set; }
        public string Coach { get; set; }
        public string Athlete { get; set; }
    
        public virtual Coaches Coaches { get; set; }
        public virtual Athletes Athletes { get; set; }
    }
}
