//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicalFit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PsychologicalTraitsResults
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public System.DateTime PsychologicalDate { get; set; }
        public string Trait { get; set; }
        public string Feeling { get; set; }
        public int Score { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Athletes Athletes { get; set; }
    }
}
