//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicalFit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RunningMachineRecord
    {
        public int ID { get; set; }
        public Nullable<int> DetectionRecordID { get; set; }
        public Nullable<double> MaxRunningSpeed { get; set; }
        public Nullable<int> TimeExhaustion { get; set; }
        public string IPercen95 { get; set; }
        public string IPercen90 { get; set; }
        public string IPercen85 { get; set; }
        public string IPercen80 { get; set; }
        public Nullable<double> SpeedResults { get; set; }
    
        public virtual DetectionTrainingRecord DetectionTrainingRecord { get; set; }
    }
}
