//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicalFit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShootingTraining
    {
        public int Id { get; set; }
        public string ItemNumber { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> BulletCount { get; set; }
        public Nullable<int> RPEScore { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string CreatedUser { get; set; }
    }
}
